### ISSUE TITLE
Installer broken (?) on Rails 7.2

### ISSUE THREAD

**Issue by julianrubisch** [fractaledmind/litestream-ruby#35]
On Rails 7.2 I'm getting

```
.../activerecord-7.2.0/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `sqlite3_production_warning=' for class ActiveRecord::Base (NoMethodError)
```

I _think_ I remember that warning has been removed by... you?

**Comment by fractaledmind** [comment]
It was removed by Xavier, but I was a part of the discussions. Will fix. Thanks for the report

**Comment by fractaledmind** [comment]
@julianrubisch: I don't see a reference to this in the codebase. Are you sure the error originates with the installer?

**Comment by julianrubisch** [comment]
I’ll double check tomorrow

**Comment by julianrubisch** [comment]
circling back... maybe this part of the stacktrace helps?

```
        from .../litestream-0.11.0-arm64-darwin/lib/litestream/generators/litestream/install_generator.rb:21:in `production_sqlite_databases'
        from .../litestream-0.11.0-arm64-darwin/lib/litestream/generators/litestream/templates/config.yml.erb:13:in `template'
```

I'll see that I can come back with an MVCE soon

**Comment by julianrubisch** [comment]
okay, disregard 🤦‍♂️  I was on an older version of litestack which was causing this... hard to discern from the stacktrace
