### ISSUE TITLE
Missing Executable [ x86_64-linux]

### ISSUE THREAD

**Issue by richjdsmith** [fractaledmind/litestream-ruby#9]
Not quite sure how to debug from here. I have tried to get it to work on two separate computers, both running Ubuntu on x86 platforms. Wondering if something changed on how it is installed?

I know litestream can be installed, and can get litestream-ruby working when I use the `LITESTREAM_INSTALL_DIR` env if I manually install litestream, but can't figure out why the gem isn't including/installing the actual executable itself.

**Comment by fractaledmind** [comment]
Interesting. I will debug. Maybe that executable failed to upload to RubyGems 🤷🏻‍♂️ I'll check.

**Comment by richjdsmith** [comment]
Thanks! Let me know if you need anything on my end. Using Ubuntu 22.04.3 LTS

**Comment by fractaledmind** [comment]
So, thanks for bringing this to my attention. For version 0.3.2, I used the wrong release script and only released the base Ruby version and not any of the additional platform versions. I just released version 0.3.3 with a fix for extra memory consumption and released that with all platform versions. That should work for you. Please ping me with confirmation that v0.3.3 installs on Linux and we can close this issue.

**Comment by richjdsmith** [comment]
Looks like that sorted it out! Thanks for fixing that, @fractaledmind !
